name: Environment and Tools

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * 0"

permissions:
  contents: write

jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Environment and Tools
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_UPDATED_DATE: true
          SECTION_NAME: Environment and Tools