name: Environment and Tools

on:
  schedule:
    - cron: "30 0 * * 0"  # runs weekly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update environment stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_LANGUAGE: false
          SHOW_TIMEZONE: false
          SECTION_NAME: Environment and Tools