name: Productivity Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write

jobs:
  productivity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: productivity
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: true
          SHOW_SHORT_INFO: true
          SHOW_UPDATED_DATE: true